# Generated by Django 2.2.4 on 2020-02-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_auto_20190820_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrun',
            name='batch_id',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
